import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { contract } from '../web3/contracts/Verify';

declare global {
  interface Window { ethereum: any; }
}

const Verify: NextPage = () => {

  const [coupon, setCoupon] = useState("");

  function splitCoupon(coupon: string) {
      const hash = coupon.slice(0, 66);
      const signature = coupon.slice(66, coupon.length);
      const r = signature.slice(0, 66);
      const s = "0x" + signature.slice(66, 130);
      const v = parseInt(signature.slice(130, 132), 16);
      const signatureParts = { r, s, v };
      return [hash, signatureParts];
  }

  async function handleVerifyCoupon() {
      const account = window.ethereum.selectedAddress;
      const couponParts = splitCoupon(coupon);
      const hash = couponParts[0];
      const signature = couponParts[1] as any;
      await contract.methods.claimCoupon(hash, signature.v, signature.r, signature.s).send({from:account});
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input type="text" placeholder="Cupom" value={coupon} onChange={e => setCoupon(e.target.value)}/>
        <button onClick={handleVerifyCoupon}>Verificar cupom</button>
      </main>
    </div>
  )
}

export default Verify;
